theme: jekyll-theme-modernist
navbar: "*quickCode **Docs*** | [**Editor**](https://webcoder49.github.io/quickCode/) | [**Docs**](https://webcoder49.github.io/quickCode/docs/) | [**Policy**](https://webcoder49.github.io/quickCode/policy)"
