theme: jekyll-theme-modernist
navbar: |
  [quickCode Editor](https://webcoder49.github.io/quickCode/) | [quickCode Docs](https://webcoder49.github.io/quickCode/docs/) | [More from WebCoder49](https://webcoder49.github.io/)
  ---
